Labb 1 - Reg/config/routes.rb
Rails.application.routes.draw do

    root  :to => redirect('/login')
  get   '/login' => 'loginsessions#new'
  post  '/login' => 'loginsessions#create'

  get   'admin_login' => 'loginsessions#new_admin', as: :login_admin
  post  'admin_login' => 'loginsessions#create_admin', as: :do_login_admin

  

  
   get   '/adminlogout' => 'loginsessions#destroy_admin', as: :logout_admin
    get   '/logout'  => 'loginsessions#destroy', as: :logout_user
  get   'api_users/:id/:api_user_id' => 'user_api_keys#destroy', as: :apikeyD
  get   'api_users/:api_user_id' => 'user_api_keys#create', as: :new_apikey
get   'api_admin/:id/:api_user_id' => 'user_api_keys#admindestroyUserkey', as: :adminApikeyD

  get   'admin' => 'admins#show', as: :admin

get '/api_users' => 'api_users#new',  as: :new_user
  
  resources :user_api_keys 
  
resources :api_users, only: [:create, :destroy, :new, :index] do
resources :user_api_keys 
end

end

Labb 1 - Reg/app/controllers/loginsessions_controller.rb
class LoginsessionsController < ApplicationController
    
  def new

  end
  
   def create_admin# admin login 
    admin = Admin.find_by(name: params[:session][:name].downcase)

    if admin && admin.authenticate(params[:session][:password])
      log_admin_in admin
      redirect_to admin_path
    else
      flash.now[:danger] = 'Bad name/password combination!'
      render 'new_admin'
    end
  end

  def create# användare login 
    user = ApiUser.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to api_user_user_api_key_path(user.id, user.id) #apikey_path #api_user_user_api_key_path 
    else
      flash.now[:danger] = 'Bad email/password combination!'
      render 'new'
    end
  end

  def destroy# logaut användare 
    log_out
    flash[:info] = 'Goodbye, You are logged out'
    redirect_to root_path
  end

 
  def destroy_admin# logaut admin
    log_admin_out
    flash[:info] = 'Goodbye, You are logged out'
    redirect_to root_path
  end
    
end

Labb 1 - Reg/app/helpers/loginsessions_helper.rb
module LoginsessionsHelper
    
     def log_in(user)
    session[:userid] = user.id
  end

  def log_out
    session.delete(:userid)
    @current_user = nil
  end
  
      def current_admin
    @current_admin ||= Admin.find_by(id: session[:adminid])
  end

  def is_admin_logged_in?
    !current_admin.nil?
  end


  def log_admin_out
    session.delete(:adminid)
    @current_admin = nil
  end

  def check_admin# kotrolerar om admin man är in logad 
    unless is_admin_logged_in?
      flash[:danger] = "login before visit this part of the application!!!"
      redirect_to root_path
    end
  end

  def current_user
    @current_user ||= ApiUser.find_by(id: session[:userid])
  end

  def is_logged_in?
    !current_user.nil?
  end
  
   def log_admin_in(admin)
    session[:adminid] = admin.id
  end

  def check_user# kontrollerar om användare är in logad 
    unless is_logged_in?
      flash[:danger] = "login before visit this part of the application!!!"
      redirect_to root_path
    end
  end
  
  
  def check# kotrolerar om admin man är in logad 
   
    if is_admin_logged_in? == true

    elsif is_logged_in? == true

    else
    flash[:danger] = "login before visit this part of the application!!!"
            redirect_to root_path
    end
    
  end

    
end

Labb 1 - Reg/app/views/loginsessions/new.html.erb
<fieldset>
    
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    
    <%= form_for(:session, url: login_path, :html => {:class => "form-signin"}) do |f| %>
        <h2 class="form-signin-heading">Sign in</h2>
        <p><%= f.label :email, "E-mail:", class: "sr-only" %></p>
        <p><%= f.email_field(:email, :required => true, placeholder: "E-mail", class: 'form-control') %></p>

        <p><%= f.label(:password, "Password:", class: "sr-only") %></p>
        <p><%= f.password_field(:password, :required => true, placeholder: "Password", class: 'form-control') %></p>

        <p><%= f.submit("Log in", class: "btn btn-lg btn-primary btn-block") %></p>
      <ul class="nav nav-pills">
        <li role="presentation"><%= link_to "Register", new_user_path %></li>
        <li role="presentation"><%= link_to "Admin login", login_admin_path %></li>
      </ul>
    <% end %>


</fieldset>

Labb 1 - Reg/app/views/loginsessions/new_admin.html.erb
<%= link_to "Back", root_path %>

<fieldset>
  
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
  
  <%= form_for(:session, url: do_login_admin_path, :html => {:class => "form-signin"}) do |f| %>
      <h2 class="form-signin-heading">Sign in as admin</h2>
      <p><%= f.label :name, "Name:", class: "sr-only" %></p>
      <p><%= f.text_field(:name,:required => true,  placeholder: "Name", class: 'form-control') %></p>

      <p><%= f.label(:password, "Password:", class: "sr-only") %></p>
      <p><%= f.password_field(:password,:required => true,  placeholder: "Password", class: 'form-control') %></p>

      <p><%= f.submit("Log in", class: "btn btn-lg btn-primary btn-block") %></p>
  <% end %>
</fieldset>