Labb 1 - Reg/config/routes.rb
Rails.application.routes.draw do

    root  :to => redirect('/login')
  get   '/login' => 'loginsessions#new'
  post  '/login' => 'loginsessions#create'

  get   'admin_login' => 'loginsessions#new_admin', as: :login_admin
  post  'admin_login' => 'loginsessions#create_admin', as: :do_login_admin

  

  
   get   '/adminlogout' => 'loginsessions#destroy_admin', as: :logout_admin
    get   '/logout'  => 'loginsessions#destroy', as: :logout_user
  get   'api_users/:id/:api_user_id' => 'user_api_keys#destroy', as: :apikeyD
  get   'api_users/:api_user_id' => 'user_api_keys#create', as: :new_apikey
get   'api_admin/:id/:api_user_id' => 'user_api_keys#admindestroyUserkey', as: :adminApikeyD

  get   'admin' => 'admins#show', as: :admin

get '/api_users' => 'api_users#new',  as: :new_user
  
  resources :user_api_keys 
  
resources :api_users, only: [:create, :destroy, :new, :index] do
resources :user_api_keys 
end

end

Labb 1 - Reg/app/views/admins/show.html.erb
<div>
  <br>
<%= link_to 'Logout', logout_admin_path, data: {no_turbolink: true}, class: "btn btn-danger btn-lg center" %>
  <br>
  <h2>Users and keys</h2>

  <table class="table table-hover">

        <% @users.each do |user| %>
            <tr>
              <td><h5>ID</h5><%= user.id %></td>
              <td><h5>E-mail</h5><%= user.email %></td>
              
              <% user.user_api_keys.each do |p| %>

              <td><h5>Key:</h5> <%= p.value %> <br> <%= link_to 'Delete ApiKey', adminApikeyD_path(p.id,p.api_user_id), :data => {:confirm => 'Are you sure?'}%></td>
        

        <% end %>
              
              <td><%= link_to 'Delete User', api_user_path(user.id), method: :delete, class: "btn btn-danger", data: { confirm: "do you want to remove this user and all api keys"} %></td>
            </tr>
        <% end %>

  </table>

</div>